### ISSUE TITLE
Where to get the manditory downloads?

### ISSUE THREAD

**Issue by totierne** [oracle/db-appdev-vm#1]
Hi,

>These two downloads are mandatory. If they are not there, the build will not start.
>    OracleLinux-R7-U3-Server-x86_64-dvd.iso (needs to be this exactly md5 checked)
Which Suggests: http://edelivery.oracle.com/linux (I cannot give more direct link - as login required)
Free, login required [slightly annoying] - and glancing at the small print - need to be over 18. 

>    linux*122*_database.zip (12201 has been verified - silent install may be incompatible with later [and earlier] versions)
[Click to accept license - takes 2 seconds]
http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html#

Blog entry: https://blogs.oracle.com/linux/oracle-linux-73-available-now

That blog currently contains the following words: "Oracle Linux can be downloaded,
used and distributed free of charge and all updates
and errata are freely available. For support, [to paraphrase: support costs money]"

Thank you for your time,
Turloch

The views expressed by Turloch O'Tierney (totierne) on github are my own and do not necessarily reflect the views of Oracle.

**Comment by totierne** [comment]
linux122_database.zip - note the name has been mangled by markup - what it should be is: 
linuxx64UNDERLINE12201UNDERLINEdatabase.zip
That also needs (free) login - so only 2 seconds if you are already logged in - I am always logged in so missed that.

**Comment by totierne** [comment]
Should move this more detailed download information to README.md

Turloch

The views expressed by Turloch O'Tierney (totierne) on github are my own and do not necessarily reflect the views of Oracle.

**Comment by bamcgill** [comment]
Merged comments in README.md
