### ISSUE TITLE
Where do I get the pre built output .ova from this build?

### ISSUE THREAD

**Issue by totierne** [oracle/db-appdev-vm#2]
Hi,

>Where do I get the pre built output .ova from this build?

output directory (or http://www.oracle.com/technetwork/database/enterprise-edition/databaseappdev-vm-161299.html )

The link versioned includes some not open sourced/not otherwise available outside Oracle items (Labs + coffeeshop 'html' demo).

Thank you for your time,
Turloch

The views expressed by Turloch O'Tierney (totierne) on github are my own and do not necessarily reflect the views of Oracle.

**Comment by bamcgill** [comment]
Added these changes to the README.md
