### ISSUE TITLE
Where else may these scripts apply?

### ISSUE THREAD

**Issue by totierne** [oracle/db-appdev-vm#3]
Hi ,

These scripts are:
1/bootstrap from iso
2/scp
3/shell script
4/A little gnome/yum stuff.

Would like to try the APEX/ORDS install on a Oracle docker script.
Likely issues: skip bootstrap from iso, gnome /u01 hard coding

Would like  to try the .ova (which is an open format)  on a (non Virtualbox) vendors virtualization.
Likely issues: I do not have enough experience on other vendors virtualization

Would like to try the scripts on a Oracle Compute Cloud offering.
Likely issues: skip bootstrap from iso, /u01 hardcoding.

Thank you for your time,
Turloch

The views expressed by Turloch O'Tierney (totierne) on github are my own and do not necessarily reflect the views of Oracle.

**Comment by bamcgill** [comment]
This is not an issue with the code.
